# Note: here we do not need a k8s service since this service does not have any web/socket API (it connects to redis, but nobody connects to it)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cstar-cmd-pod-rs-dep
  namespace: default
  labels:
    run: cstar-cmd-pod-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cstar-cmd-pod-rs
  template:
    metadata:
      labels:
        run: cstar-cmd-pod-rs
    spec:
      # volumes:
      #   - name: cstar-cmd-pod-rs-src
      #     hostPath:
      #       path: '{{dir_abs}}/services/cmd-pod-rs/src'
      #       type: Directory
      #   - name: cstar-cmd-pod-rs-cargo-toml
      #     hostPath:
      #       path: '{{dir_abs}}/services/cmd-pod-rs/Cargo.toml'
      #       type: File            
      containers:
        - image: "localhost:5000/cstar-cmd-pod-rs:{{image_tag}}"
          name: cstar-cmd-pod-rs-ctn
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cstar-config
            - secretRef:
                name: cstar-secret
          env:
            - name: service_name
              value: cmd-pod-rs          
          # volumeMounts:
          #   - mountPath: /service/src
          #     name: cstar-cmd-pod-rs-src
          #   - mountPath: /service/Cargo.toml
          #     name: cstar-cmd-pod-rs-cargo-toml
      restartPolicy: Always
