Handlebars.templates['spec-buttons']  = Handlebars.template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<!-- <origin src=\"https://raw.githubusercontent.com/BriteSnow/cloud-starter/master/frontends/web/src/views/spec/spec-buttons.tmpl\" /> -->\n\n<div class=\"card wide\">\n	<header>\n		<h1>Buttons</h1>\n	</header>\n	<section>\n\n		<h2>Active</h2>\n		<h2>Disabled</h2>\n\n		<!-- Default Buttons-->\n		<div>\n			<a class=\"button\" href=\"#buttons\">button</a>\n		</div>\n		<div>\n			<a class=\"button disabled\">button</a>\n		</div>\n\n		<!-- Small Buttons-->\n		<div>\n			<a class=\"button small\" href=\"#buttons\">small</a>\n		</div>\n		<div>\n			<a class=\"button small disabled\">small</a>\n		</div>\n\n\n		<!-- Medium Buttons-->\n		<div>\n			<button class=\"medium\">\n				<c-ico>user</c-ico> Medium button\n			</button>\n		</div>\n		<div>\n			<button class=\"medium\" disabled>Medium button</button>\n		</div>\n\n		<div>\n			<button class=\"high\">high button</button>\n		</div>\n		<div>\n			<button class=\"high\" disabled>high button</button>\n		</div>\n\n\n		<div>\n			<button class=\"outlined\">outlined button</button>\n		</div>\n		<div>\n			<button class=\"outlined\" disabled>outlined button</button>\n		</div>\n\n		<div>\n			<button class=\"main-button\">\n				<c-ico>user</c-ico>\n			</button>\n		</div>\n\n	</section>\n</div>\n\n<!-- Action Link -->\n\n\n<div class=\"card wide\">\n	<header>\n		<h1>Buttons</h1>\n	</header>\n	<section>\n\n		<h2>Active</h2>\n		<h2>Disabled</h2>\n\n		<div>\n			<div class=\"action-link\">action-link div</div>\n		</div>\n		<div>\n			<div class=\"action-link\" disabled>action-link div</div>\n		</div>\n		<!-- Action Link -->\n		<div>\n			<div class=\"action-link small\">action-link small div</div>\n		</div>\n		<div>\n			<div class=\"action-link small\" disabled>action-link small div</div>\n		</div>\n	</section>\n</div>";
},"useData":true});


Handlebars.templates['spec-cards']  = Handlebars.template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<!-- <origin src=\"https://raw.githubusercontent.com/BriteSnow/cloud-starter/master/frontends/web/src/views/spec/spec-cards.tmpl\" /> -->\n\n<div class=\"card\">\n	<header><h2>Base Card</h2></header>\n	<section>\n		some long content some long content some long content some long content some long content some long content \n	</section>\n</div>\n\n<div class=\"card\">\n	<header>\n		<h2>Card With</h2>\n		<h3>subtitle and footer</h3>\n	</header>\n	<section>\n		some long content some long content some long content some long content some long content some long content \n	</section>\n	<footer class=\"split-2\"r>\n		<div>\n			<button>button</button>\n		</div>\n		<div>\n			<c-ico>user</c-ico>\n			<c-ico>share</c-ico>\n		</div>\n	</footer>\n</div>	\n\n<div class=\"card wide\">\n	<header><h2>Card With Aside</h2>\n		<aside><c-ico>more</c-ico></aside>\n	</header>\n	<section>\n		some long content some long content some long content some long content some long content some long content \n	</section>\n</div>		\n\n<div class=\"card tall wide\">\n	<header><h2>Card with some long content</h2></header>\n	<section>\n	some long content some long content some long content some long content some long content some long content \n	</section>\n	<footer>Some footer</footer>\n</div>		";
},"useData":true});


Handlebars.templates['spec-controls']  = Handlebars.template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<!-- <origin src=\"https://raw.githubusercontent.com/BriteSnow/cloud-starter/master/frontends/web/src/views/spec/spec-controls.tmpl\" /> -->\n\n<div class=\"card spec-inputs\">\n	<header>\n		<h2>c-input</h2>\n	</header>\n\n	<section>\n		<c-input label=\"(readonly)\" name=\"fieldA\" value=\"value A\" readonly ></c-input>\n		<c-input label=\"(disabled)\" name=\"fieldB\" value=\"value B\" disabled></c-input>\n		<c-input label=\"Normal\" name=\"fieldC\" value=\"value C\"></c-input>\n		<c-input label=\"No value\" name=\"fieldD\" placeholder=\"With place holder\"></c-input>\n		<c-input label=\"No value, no placeholder\" name=\"fieldE\"></c-input>\n		<c-input name=\"fieldF\" value=\"no label, with value and placeholder\" placeholder=\"....placeholder...\"></c-input>\n		<c-input name=\"fieldG\" placeholder=\"no label, no value, only placeholder\"></c-input>\n	</section>\n	<footer><button class=\"do-push\">push</button></footer>\n</div>\n\n<div class=\"card spec-selects\">\n		<header>\n			<h2>c-select</h2>\n		</header>\n		<section>\n			<c-select label=\"Field G\" name=\"fieldG\" value=\"G\" readonly>\n				<option value=\"one\">value one</option>\n				<option value=\"G\">value G (readonly)</option>\n			</c-select>\n\n			<c-select name=\"fieldH\" disabled>\n					<option>No Value &amp; Disabled</option>\n					<option value=\"one\">value one</option>\n					<option value=\"H\">value H</option>\n			</c-select>\n\n			<c-select name=\"fieldI\" placeholder=\"Placeholder with no value and no null option\">\n					<option value=\"one\">value one</option>\n					<option value=\"I\">value I</option>\n			</c-select>\n\n			<c-select name=\"fieldJ\" placeholder=\"Placeholder with no value but a null option\">\n					<option>None</option>\n					<option value=\"one\">value one</option>\n					<option value=\"J\">value J</option>\n			</c-select>\n\n			<c-select name=\"fieldK\" value=\"K\">Value K (load on demand)</c-select>\n\n		</section>\n		<footer><button class=\"do-push\">push</button></footer>\n	</div>\n\n<div class=\"card spec-checks\">\n	<header>\n		<h2>c-check</h2>\n	</header>\n	<section>\n		<c-check name=\"fieldD\" value=\"value D\" checked></c-check>\n		<c-check name=\"fieldE\"></c-check>\n		<c-check name=\"fieldF\" value=\"value F\"></c-check>\n	</section>\n	<footer><button class=\"do-push\">push</button></footer>\n</div>\n\n\n\n<div class=\"card spec-options\">\n	<header>\n		<h2>c-options</h2>\n	</header>\n	<section>\n		<c-options name=\"state\" options=\"1:Open, 0:Close, 2 : Both\" value=\"0\"></c-options>\n	</section>\n	<footer></footer>			\n</div>\n	";
},"useData":true});


Handlebars.templates['spec-dialogs']  = Handlebars.template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<!-- <origin src=\"https://raw.githubusercontent.com/BriteSnow/cloud-starter/master/frontends/web/src/views/spec/spec-dialogs.tmpl\" /> -->\n\n<div class=\"card wide\">\n	<section>\n		<section>\n			<div class=\"dialog\" style=\"width: 20rem; margin: 1rem 0 0 1rem\">\n				<header><h2>Dialog 1</h2><c-ico class=\"action do-close\">close</c-ico></header>\n				<section class=\"message\">\n					<p>\n						Some working is going on\n						Some working is going on\n						Some working is going on\n						Some working is going on\n						Some working is going on\n						Some working is going on\n					</p>\n				</section>\n				<footer>\n					<button>Close</button>\n				</footer>\n			</div>\n		</section>\n		<section>\n			<button class=\"show-dialog2\">Dialog 2</button>\n		</section>\n	</section>\n</div>\n\n<div class=\"card wide\">\n		<header><h2>Menu</h2></header>\n		<section class=\"position:relative\">\n			<c-menu>\n				<div>One</div>\n				<div>Two</div>\n				<div>Longer Menu Item</div>\n			</c-menu>\n		</section>\n</div>		\n	";
},"useData":true});


Handlebars.templates['spec-typo']  = Handlebars.template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<!-- <origin src=\"https://raw.githubusercontent.com/BriteSnow/cloud-starter/master/frontends/web/src/views/spec/spec-typo.tmpl\" /> -->\n\n<div class=\"card\">\n	<header><h2>Typography Headings</h2></header>\n	<section class=\"content\">\n		<h1>H1</h1>\n		<h2>H2</h2>\n		<h3>H3</h3>\n		<h4>H4</h4>\n		<h5>H5</h5>\n		<h6>H6</h6>\n	</section>\n</div>\n\n<div class=\"card\">\n		<header><h2>Typography Others</h2></header>\n		<section class=\"content\">\n			<div class=\"sub1\">sub1</div>\n			<div class=\"sub2\">sub2</div>\n			<div class=\"body1\">body1</div>\n			<div class=\"body2\">body2</div>\n			<div class=\"txt-button\">txt-button</div>\n			<div class=\"caption\">caption</div>\n			<div class=\"overline\">overline</div>\n		</section>\n</div>	";
},"useData":true});

