# Note: here we do not need a k8s service since this service does not have any web/socket API (it connects to redis, but nobody connects to it)
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cstar-cmd-pod
  name: cstar-cmd-pod-dep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cstar-cmd-pod
  template:
    metadata:
      labels:
        run: cstar-cmd-pod
    spec:
      containers:
        - image: '{{registry}}cstar-cmd-pod:{{image_tag}}'
          name: cstar-cmd-pod-ctn
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cstar-config
            - secretRef:
                name: cstar-secret
      restartPolicy: Always
